  apiVersion: serving.knative.dev/v1
  kind: Service
  metadata:
    name: helloworld-python
    namespace: default
  spec:
    template:
      spec:
        containers:
          - image: gvaquerog/helloworld-python:1.0
            imagePullPolicy: Never
            env:
              - name: TARGET
                value: "Python Sample v1"